require "httparty"
require "core_ext/hash"

require "cameraplus/api/request"
require "cameraplus/api/base"
require "cameraplus/api/user"
require "cameraplus/api/page"
require "cameraplus/api/search"

require "cameraplus/user"
require "cameraplus/page"
require "cameraplus/page_metadata"
require "cameraplus/photo"
require "cameraplus/photo_exif"
require "cameraplus/photo_recipe"
require "cameraplus/comment"
require "cameraplus/search"
require "cameraplus/exceptions"
require "cameraplus/version"
